# Site specific settings
title: "TheDoom"
name: "K0deless' TheDoom"
keywords: "reversing, malware, C, C++, ASM, Social Engineering, Pentesting"
baseurl: ""
url: "https://k0deless.github.io"
description: "UC3M Cybersecurity students webpage, where you'll find our research posts, papers and so on."
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "jp"
ssl: true # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter:  
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
